### PR TITLE
Changed 'iOS' to 'Android' for the supply tool

### PR DESCRIPTION
**Pull request by azgul**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Oh, nice catch, thanks. This should actually be `Command line tool for updating Android apps and their metadata on the Google Play Store`. Do you want to update the PR?

**Comment by azgul** [comment]
Sure, give me a minute :+1:

**Comment by KrauseFx** [comment]
Perfect, thank you @azgul :+1:

**Comment by azgul** [comment]
No problem.

**Pull request merged**
