### PR TITLE
Added README.md with setup instructions and did some SEO on web pages

### PR DESCRIPTION
**Pull request by brennanMKE**
It looked like search results for fastlane and Jenkins were buried and the pages which were coming up first were not specific to Jenkins and fastlane. I added meta keywords to the home page and created a new page in a folder named `jenkins` which can help with SEO. I'm no SEO expert but I figure this will help a little.

Perhaps more details from the markdown page for Jenkins could be put onto this new page to further enhance the page rank. It would also help to encourage more links to this Jenkins page to boost the page rank.

A tutorial to set up fastlane with Jenkins could be listed on this page.

http://jenkins-ci.org/views/hudson-tutorials

If that tutorial then linked to this new Jenkins page it should boost the page rank. Since Jenkins is already used very widely and people looking into fastlane are likely interested in integrated them, making this content more discoverable could ease that transition to using fastlane.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @brennanMKE thanks for the pull request :+1: 

I'm not sure, why we would want a separate Jenkins page? `fastlane` doesn't do anything Jenkins specific, it's just an example use case. I don't want `fastlane` to be associated with Jenkins.

I'd suggest we remove the Jenkins page and change the keywords to `iOS, iPhone, iPad, Mac, Xcode, Signing, Continuous, Deployment, Delivery, Integration, Automation, Jenkins`

**Comment by brennanMKE** [comment]
A page will get a higher page rank if the keyword is in the URL. Since many people will want to set up Jenkins with fastlane I thought it would be good to make it easier to find. The people setting this up may be more on the IT side than the software development side so keeping that in mind may help people leverage fastlane to automate their builds and other tasks which fastlane supports.

I don't think the keywords carry a whole lot of weight since they have been abused over the years. I just put a few in there on the off chance it might help. What I know will help the most will be that distinct page dedicated to linking to Jenkins content related to fastlane. Perhaps you could ask fastlane users who are integrating with Jenkins to share blog posts on how they use it. Linking to those blog posts would be helpful.

**Comment by KrauseFx** [comment]
@brennanMKE when you google for `fastlane jenkins`, the first result is https://github.com/KrauseFx/fastlane/issues/89, which explains how to setup both `fastlane` and Jenkins. I don't think we should have an extra site on fastlane.tools just for Jenkins.

**Comment by brennanMKE** [comment]
This page is the one URL that you can control and optimize for the purpose of better helping Jenkins users to get started with fastlane. The page for issue 89 is good now but it won't always be the best place to start.

If this page points to issue 89 and any blog posts or tutorials for integrating a CI service with fastlane it would be linked to by many other sites, boosting the page ranking. You can even put a comment on the page asking people to share links to blog posts and tutorials so they can be included on that page which will encourage people to write that very helpful content.

Another point to consider is the audience. You and I come from the perspective of software developers. For IT admins, who often manage CI servers, GitHub and source control are outside their area of expertise. They want to stay far away from source code and just want step by step instructions. The moment they see source code they turn away. I've seen it many times. By providing a page for this audience it will help IT admins adopt fastlane.

**Comment by KrauseFx** [comment]
Sorry, I really don't want a separate page for Jenkins on fastlane.tools. But the README is nice. Would you mind updating the pull request to only include the new README?

**Pull request closed without merging**
