### PR TITLE
Favicon :)

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

**Comment by KrauseFx** [comment]
The favicon is never linked, right? https://github.com/fastlane/fastlane.tools/blob/gh-pages/index.html#L5-L11

**Comment by lacostej** [comment]
Most browsers fetch it automatically anyway

https://en.wikipedia.org/wiki/Favicon#How_to_use

But we could/should add a link from the index for explicit stating.

**Comment by KrauseFx** [comment]
Perfect, thanks :+1:

**Comment by KrauseFx** [comment]
It works :rocket:

**Comment by lacostej** [comment]
hehe now I just need to closee enough tabs from my browser to see it :)

**Pull request merged**
